---
version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - "$HOME/.deepforge/data:/data/db"
  server:
    environment:
      - "MONGO_URI=mongodb://mongo:27017/deepforge"
      - "NODE_ENV=default"
    image: deepforge/kitchen-sink:latest
    ports:
      - "8888:8888"
      - "8889:8889"
    volumes:
      - "$HOME/.deepforge/blob:/data/blob"
    depends_on:
      - mongo
